version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "hr_system"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  hr-system:
    image: n960321/hr-system:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./hr-system/configs:/app/configs
    depends_on:
      mysql:
        condition: service_healthy

        
